FROM node:16-alpine3.11

WORKDIR /app_frontend

ENV HOST=0.0.0.0
ENV PORT=3000

RUN npm i -g @nestjs/cli

COPY . .

EXPOSE 3000

# Dependencies from package.json and start the server
ENTRYPOINT npm install && npm run start
